services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8080:8000"

  frontend:
    image: nginx:1.25
    depends_on:
      - api
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  dbdata:

