apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: cfg
          configMap:
            name: frontend-config
      containers:
        - name: nginx
          image: nginx:1.25
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            # mount index.html directly to where nginx serves it
            - name: cfg
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            # drop our server block into conf.d (nginx includes it by default)
            - name: cfg
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          # keep probes simple to avoid flapping during start
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
