apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
   app: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
