apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: db
  ports:
    - name: postgres
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  type: ClusterIP
