name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/three-tier-api:sha-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API image
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Print image tag
        run: echo "Pushed image: $IMAGE"
